### ISSUE TITLE
Add CSS Styling

### ISSUE THREAD

**Issue by ryenski** [BoosterStage/issue-tracker#1]
The app doesn't look very nice. Let's make it look pretty.

**Comment by mysmallidea** [comment]
## Resolve issues
Let’s add the ability to resolve an issue. 

We need to add a column to our Issues table, so let’s generate a migration. In your terminal, type: 

```bash
rails g migration AddResolvedAtToIssues resolved_at:datetime
```

open up the migration file and take a look

Run `rails db:migrate` and look at the output. 

### Add a “Close Issue” button

Open `_form.html.erb` and add

```erb
<%= link_to "Resolve Issue", resolve_issue_path, method: :put, class: "btn btn-warning" %>
```

Reload the page. We get a NameError exception because `close_issue_path` doesn’t exist. Let’s add it. 

Open `routes.rb` and add: 

```ruby
    resources :issues do
      member do
        put 'resolve'
      end
    end
```
